SCR_MissionHeader {
 World "{32BB0F14C30E9C66}Worlds/Eden/ShootingStar_Ep1.ent"
 m_sName "Operation «Shooting Star». Episode 1"
 m_sAuthor "[TT]Jumbo"
 m_sDescription "A combat engagement between Soviet Naval Infantry and US Green Berets on the island of Everon"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 128
 m_eSaveTypes 0
}