SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{6A55242C0C621CBE}" {
   m_sEntityPrefab "{314AE020EC45DAB7}Prefabs/Groups/BLUFOR/Green Berets/TSS_Group_US_GB_CompanyHQ.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6A55242C0C621CFD}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6A55242C0C621CE1}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{6A55242C1676A94A}" {
   m_sEntityPrefab "{0B0A5A93D86EDDF2}Prefabs/Groups/BLUFOR/Green Berets/TSS_Group_US_GB_SplitTeamAlpha.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6A55242C1676AA84}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6A55242C1676AA88}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{6A55242C1392ACED}" {
   m_sEntityPrefab "{C5DCFAF7FE9D8A24}Prefabs/Groups/BLUFOR/Green Berets/TSS_Group_US_GB_SplitTeamBravo.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6A55242C1392AC27}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6A55242C1392AC28}" {
     m_eSlotTypes 7
    }
   }
  }
 }
}