StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{6A532E110A41D230}" {
   Id "TSS-Characters_AsstDetachmentCommander"
   Target_en_us "Assistant Detachment Commander"
   Modified 1783845143
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6A532E0EBC97631C}" {
   Id "TSS-Characters_CommsSergeant"
   Target_en_us "Communications Sergeant"
   Modified 1783843254
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6A532E19757AFF25}" {
   Id "TSS-Characters_CompanyCommander"
   Target_en_us "Company Commander"
   Modified 1783848660
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6A532E1AE82AE9BD}" {
   Id "TSS-Characters_CompanyXO"
   Target_en_us "Company Executive Officer"
   Modified 1783849115
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6A532E11DF4E15CA}" {
   Id "TSS-Characters_DetachmentCommander"
   Target_en_us "Detachment Commander"
   Modified 1783844553
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6A532E17105B71B5}" {
   Id "TSS-Characters_EngineerSergeant"
   Target_en_us "Engineer Sergeant"
   Modified 1783847921
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6A532E14C860B86F}" {
   Id "TSS-Characters_IntelSergeant"
   Target_en_us "Intelligence Sergeant"
   Modified 1783846180
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6A532E17287A9C50}" {
   Id "TSS-Characters_MedicalSergeant"
   Target_en_us "Medical Sergeant"
   Modified 1783847823
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6A532E14ECA0288A}" {
   Id "TSS-Characters_OperationsSergeant"
   Target_en_us "Operations Sergeant"
   Modified 1783846133
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6A532E15042C86BC}" {
   Id "TSS-Characters_WeaponsSergeant"
   Target_en_us "Weapons Sergeant"
   Modified 1783846971
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6A55242CD407CCBB}" {
   Id "TSS-Groups_CompanyHQ"
   Target_en_us "Company HQ"
   Modified 1783967151
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6A55242DC8B300F0}" {
   Id "TSS-Groups_SplitTeamAlpha"
   Target_en_us "Split Team Alpha"
   Modified 1783966623
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6A55242DAAF1400B}" {
   Id "TSS-Groups_SplitTeamBravo"
   Target_en_us "Split Team Bravo"
   Modified 1783966676
   Author "siwi1"
   LastChanged "siwi1"
  }
 }
}